
insert into SYS_RESOURCES_T (RESOURCE_ID, RESOURCE_NAME, RESOURCE_DESC, RESOURCE_TYPE, RESOURCE_STRING, PARENT_ID, RES_URL, PRIORITY, ENABLED, ISSYS, MODULE, ATTRIBUTE1, ATTRIBUTE2, ATTRIBUTE3, ATTRIBUTE4, ATTRIBUTE5, ATTRIBUTE6, ATTRIBUTE7, ATTRIBUTE8, ATTRIBUTE9, ATTRIBUTE10, ORDER_CODE, CREATED_USER, CREATED_DATE, UPDATE_LAST_USER, UPDATE_LAST_DATE, VALID_FLAG, ICON)
values (1, 'zh_cn=HOME,zh_en=Home', '系统首页，根目录', '1', null, null, '/', 1, 1, 0, null, null, null, null, null, null, null, null, null, null, null, 1, null, SYSDATE, null, SYSDATE, 1, null);

insert into SYS_RESOURCES_T (RESOURCE_ID, RESOURCE_NAME, RESOURCE_DESC, RESOURCE_TYPE, RESOURCE_STRING, PARENT_ID, RES_URL, PRIORITY, ENABLED, ISSYS, MODULE, ATTRIBUTE1, ATTRIBUTE2, ATTRIBUTE3, ATTRIBUTE4, ATTRIBUTE5, ATTRIBUTE6, ATTRIBUTE7, ATTRIBUTE8, ATTRIBUTE9, ATTRIBUTE10, ORDER_CODE, CREATED_USER, CREATED_DATE, UPDATE_LAST_USER, UPDATE_LAST_DATE, VALID_FLAG, ICON)
values (2, 'Product', null, '0', null, 1, null, 1, 1, 0, null, null, null, null, null, null, null, null, null, null, null, 48, 0, SYSDATE, 0, SYSDATE, 1, null);

insert into SYS_RESOURCES_T (RESOURCE_ID, RESOURCE_NAME, RESOURCE_DESC, RESOURCE_TYPE, RESOURCE_STRING, PARENT_ID, RES_URL, PRIORITY, ENABLED, ISSYS, MODULE, ATTRIBUTE1, ATTRIBUTE2, ATTRIBUTE3, ATTRIBUTE4, ATTRIBUTE5, ATTRIBUTE6, ATTRIBUTE7, ATTRIBUTE8, ATTRIBUTE9, ATTRIBUTE10, ORDER_CODE, CREATED_USER, CREATED_DATE, UPDATE_LAST_USER, UPDATE_LAST_DATE, VALID_FLAG, ICON)
values (3, 'SHOP', null, '0', null, 1, null, 1, 1, 0, null, null, null, null, null, null, null, null, null, null, null, 79, 0, SYSDATE, 0, SYSDATE, 1, null);

insert into SYS_RESOURCES_T (RESOURCE_ID, RESOURCE_NAME, RESOURCE_DESC, RESOURCE_TYPE, RESOURCE_STRING, PARENT_ID, RES_URL, PRIORITY, ENABLED, ISSYS, MODULE, ATTRIBUTE1, ATTRIBUTE2, ATTRIBUTE3, ATTRIBUTE4, ATTRIBUTE5, ATTRIBUTE6, ATTRIBUTE7, ATTRIBUTE8, ATTRIBUTE9, ATTRIBUTE10, ORDER_CODE, CREATED_USER, CREATED_DATE, UPDATE_LAST_USER, UPDATE_LAST_DATE, VALID_FLAG, ICON)
values (4, 'BLOG', null, '0', null, 1, null, 1, 1, 0, null, null, null, null, null, null, null, null, null, null, null, 76, 0, SYSDATE, 0, SYSDATE, 1, null);

insert into SYS_RESOURCES_T (RESOURCE_ID, RESOURCE_NAME, RESOURCE_DESC, RESOURCE_TYPE, RESOURCE_STRING, PARENT_ID, RES_URL, PRIORITY, ENABLED, ISSYS, MODULE, ATTRIBUTE1, ATTRIBUTE2, ATTRIBUTE3, ATTRIBUTE4, ATTRIBUTE5, ATTRIBUTE6, ATTRIBUTE7, ATTRIBUTE8, ATTRIBUTE9, ATTRIBUTE10, ORDER_CODE, CREATED_USER, CREATED_DATE, UPDATE_LAST_USER, UPDATE_LAST_DATE, VALID_FLAG, ICON)
values (5, 'Import Export', null, '0', null, 1, null, 1, 1, 0, null, null, null, null, null, null, null, null, null, null, null, 18, 0, SYSDATE, 0, SYSDATE, 1, null);

insert into SYS_RESOURCES_T (RESOURCE_ID, RESOURCE_NAME, RESOURCE_DESC, RESOURCE_TYPE, RESOURCE_STRING, PARENT_ID, RES_URL, PRIORITY, ENABLED, ISSYS, MODULE, ATTRIBUTE1, ATTRIBUTE2, ATTRIBUTE3, ATTRIBUTE4, ATTRIBUTE5, ATTRIBUTE6, ATTRIBUTE7, ATTRIBUTE8, ATTRIBUTE9, ATTRIBUTE10, ORDER_CODE, CREATED_USER, CREATED_DATE, UPDATE_LAST_USER, UPDATE_LAST_DATE, VALID_FLAG, ICON)
values (6, 'About', null, '0', null, 1, null, 1, 1, 0, null, null, null, null, null, null, null, null, null, null, null, 54, 0, SYSDATE, 0, SYSDATE, 1, null);

insert into SYS_RESOURCES_T (RESOURCE_ID, RESOURCE_NAME, RESOURCE_DESC, RESOURCE_TYPE, RESOURCE_STRING, PARENT_ID, RES_URL, PRIORITY, ENABLED, ISSYS, MODULE, ATTRIBUTE1, ATTRIBUTE2, ATTRIBUTE3, ATTRIBUTE4, ATTRIBUTE5, ATTRIBUTE6, ATTRIBUTE7, ATTRIBUTE8, ATTRIBUTE9, ATTRIBUTE10, ORDER_CODE, CREATED_USER, CREATED_DATE, UPDATE_LAST_USER, UPDATE_LAST_DATE, VALID_FLAG, ICON)
values (7, 'Contact', null, '0', null, 1, null, 1, 1, 0, null, null, null, null, null, null, null, null, null, null, null, 68, 0, SYSDATE, 0, SYSDATE, 1, null);

insert into SYS_RESOURCES_T (RESOURCE_ID, RESOURCE_NAME, RESOURCE_DESC, RESOURCE_TYPE, RESOURCE_STRING, PARENT_ID, RES_URL, PRIORITY, ENABLED, ISSYS, MODULE, ATTRIBUTE1, ATTRIBUTE2, ATTRIBUTE3, ATTRIBUTE4, ATTRIBUTE5, ATTRIBUTE6, ATTRIBUTE7, ATTRIBUTE8, ATTRIBUTE9, ATTRIBUTE10, ORDER_CODE, CREATED_USER, CREATED_DATE, UPDATE_LAST_USER, UPDATE_LAST_DATE, VALID_FLAG, ICON)
values (8, 'System Management', null, '0', null, 1, null, 1, 1, 0, null, null, null, null, null, null, null, null, null, null, null, 0, 0, SYSDATE, 0, SYSDATE, 1, null);

insert into SYS_RESOURCES_T (RESOURCE_ID, RESOURCE_NAME, RESOURCE_DESC, RESOURCE_TYPE, RESOURCE_STRING, PARENT_ID, RES_URL, PRIORITY, ENABLED, ISSYS, MODULE, ATTRIBUTE1, ATTRIBUTE2, ATTRIBUTE3, ATTRIBUTE4, ATTRIBUTE5, ATTRIBUTE6, ATTRIBUTE7, ATTRIBUTE8, ATTRIBUTE9, ATTRIBUTE10, ORDER_CODE, CREATED_USER, CREATED_DATE, UPDATE_LAST_USER, UPDATE_LAST_DATE, VALID_FLAG, ICON)
values (10, 'zh_cn=国际化,zh_en=international', null, '0', null, 8, null, 1, 1, 0, null, null, null, null, null, null, null, null, null, null, null, 65, 0, SYSDATE, 0, SYSDATE, 1, null);

insert into SYS_RESOURCES_T (RESOURCE_ID, RESOURCE_NAME, RESOURCE_DESC, RESOURCE_TYPE, RESOURCE_STRING, PARENT_ID, RES_URL, PRIORITY, ENABLED, ISSYS, MODULE, ATTRIBUTE1, ATTRIBUTE2, ATTRIBUTE3, ATTRIBUTE4, ATTRIBUTE5, ATTRIBUTE6, ATTRIBUTE7, ATTRIBUTE8, ATTRIBUTE9, ATTRIBUTE10, ORDER_CODE, CREATED_USER, CREATED_DATE, UPDATE_LAST_USER, UPDATE_LAST_DATE, VALID_FLAG, ICON)
values (9, 'zh_cn=System Menu,zh_en=System Menu', null, '0', null, 8, null, 1, 1, 0, null, null, null, null, null, null, null, null, null, null, null, 52, 0, SYSDATE, 0, SYSDATE, 1, null);

insert into SYS_RESOURCES_T (RESOURCE_ID, RESOURCE_NAME, RESOURCE_DESC, RESOURCE_TYPE, RESOURCE_STRING, PARENT_ID, RES_URL, PRIORITY, ENABLED, ISSYS, MODULE, ATTRIBUTE1, ATTRIBUTE2, ATTRIBUTE3, ATTRIBUTE4, ATTRIBUTE5, ATTRIBUTE6, ATTRIBUTE7, ATTRIBUTE8, ATTRIBUTE9, ATTRIBUTE10, ORDER_CODE, CREATED_USER, CREATED_DATE, UPDATE_LAST_USER, UPDATE_LAST_DATE, VALID_FLAG, ICON)
values (80, 'zh_cn=Lookup Manager,zh_en=Lookup Manager', null, '0', null, 8, null, 1, 1, 0, null, null, null, null, null, null, null, null, null, null, null, 0, 0, SYSDATE, 0, SYSDATE, 1, null);

insert into SYS_RESOURCES_T (RESOURCE_ID, RESOURCE_NAME, RESOURCE_DESC, RESOURCE_TYPE, RESOURCE_STRING, PARENT_ID, RES_URL, PRIORITY, ENABLED, ISSYS, MODULE, ATTRIBUTE1, ATTRIBUTE2, ATTRIBUTE3, ATTRIBUTE4, ATTRIBUTE5, ATTRIBUTE6, ATTRIBUTE7, ATTRIBUTE8, ATTRIBUTE9, ATTRIBUTE10, ORDER_CODE, CREATED_USER, CREATED_DATE, UPDATE_LAST_USER, UPDATE_LAST_DATE, VALID_FLAG, ICON)
values (83, 'zh_cn=数据字典,zh_en=Register', null, '0', null, 8, null, 1, 1, 0, null, null, null, null, null, null, null, null, null, null, null, 54, 0, SYSDATE, 0, SYSDATE, 1, null);

insert into SYS_RESOURCES_T (RESOURCE_ID, RESOURCE_NAME, RESOURCE_DESC, RESOURCE_TYPE, RESOURCE_STRING, PARENT_ID, RES_URL, PRIORITY, ENABLED, ISSYS, MODULE, ATTRIBUTE1, ATTRIBUTE2, ATTRIBUTE3, ATTRIBUTE4, ATTRIBUTE5, ATTRIBUTE6, ATTRIBUTE7, ATTRIBUTE8, ATTRIBUTE9, ATTRIBUTE10, ORDER_CODE, CREATED_USER, CREATED_DATE, UPDATE_LAST_USER, UPDATE_LAST_DATE, VALID_FLAG, ICON)
values (18, 'zh_cn=Security Manager,zh_en=Security Manager', null, '0', null, 8, null, 1, 1, 0, null, null, null, null, null, null, null, null, null, null, null, 36, 0, SYSDATE, 0, SYSDATE, 1, null);

insert into SYS_RESOURCES_T (RESOURCE_ID, RESOURCE_NAME, RESOURCE_DESC, RESOURCE_TYPE, RESOURCE_STRING, PARENT_ID, RES_URL, PRIORITY, ENABLED, ISSYS, MODULE, ATTRIBUTE1, ATTRIBUTE2, ATTRIBUTE3, ATTRIBUTE4, ATTRIBUTE5, ATTRIBUTE6, ATTRIBUTE7, ATTRIBUTE8, ATTRIBUTE9, ATTRIBUTE10, ORDER_CODE, CREATED_USER, CREATED_DATE, UPDATE_LAST_USER, UPDATE_LAST_DATE, VALID_FLAG, ICON)
values (11, 'zh_cn=用户管理,zh_en=Users Manager', null, '0', null, 18, null, 1, 1, 0, null, null, null, null, null, null, null, null, null, null, null, 14, 0, SYSDATE, 0, SYSDATE, 1, null);

insert into SYS_RESOURCES_T (RESOURCE_ID, RESOURCE_NAME, RESOURCE_DESC, RESOURCE_TYPE, RESOURCE_STRING, PARENT_ID, RES_URL, PRIORITY, ENABLED, ISSYS, MODULE, ATTRIBUTE1, ATTRIBUTE2, ATTRIBUTE3, ATTRIBUTE4, ATTRIBUTE5, ATTRIBUTE6, ATTRIBUTE7, ATTRIBUTE8, ATTRIBUTE9, ATTRIBUTE10, ORDER_CODE, CREATED_USER, CREATED_DATE, UPDATE_LAST_USER, UPDATE_LAST_DATE, VALID_FLAG, ICON)
values (12, 'zh_cn=角色管理,zh_en=Role Manager', null, '0', null, 18, null, 1, 1, 0, null, null, null, null, null, null, null, null, null, null, null, 26, 0, SYSDATE, 0, SYSDATE, 1, null);

insert into SYS_RESOURCES_T (RESOURCE_ID, RESOURCE_NAME, RESOURCE_DESC, RESOURCE_TYPE, RESOURCE_STRING, PARENT_ID, RES_URL, PRIORITY, ENABLED, ISSYS, MODULE, ATTRIBUTE1, ATTRIBUTE2, ATTRIBUTE3, ATTRIBUTE4, ATTRIBUTE5, ATTRIBUTE6, ATTRIBUTE7, ATTRIBUTE8, ATTRIBUTE9, ATTRIBUTE10, ORDER_CODE, CREATED_USER, CREATED_DATE, UPDATE_LAST_USER, UPDATE_LAST_DATE, VALID_FLAG, ICON)
values (13, 'zh_cn=资源管理,zh_en=Resources Manager', null, '0', null, 18, null, 1, 1, 0, null, null, null, null, null, null, null, null, null, null, null, 69, 0, SYSDATE, 0, SYSDATE, 1, null);

insert into SYS_RESOURCES_T (RESOURCE_ID, RESOURCE_NAME, RESOURCE_DESC, RESOURCE_TYPE, RESOURCE_STRING, PARENT_ID, RES_URL, PRIORITY, ENABLED, ISSYS, MODULE, ATTRIBUTE1, ATTRIBUTE2, ATTRIBUTE3, ATTRIBUTE4, ATTRIBUTE5, ATTRIBUTE6, ATTRIBUTE7, ATTRIBUTE8, ATTRIBUTE9, ATTRIBUTE10, ORDER_CODE, CREATED_USER, CREATED_DATE, UPDATE_LAST_USER, UPDATE_LAST_DATE, VALID_FLAG, ICON)
values (14, 'zh_cn=权限配置,zh_en=authorities Manager', null, '0', null, 18, null, 1, 0, 0, null, null, null, null, null, null, null, null, null, null, null, 50, 0, SYSDATE, 0, SYSDATE, 1, null);

COMMIT;
